Pipeline/resnet50 feature extractor
hearai/hearai pull request #10
Opened 2022-01-03 11:33 UTC by mariaogryczak

2022-01-03 14:26 UTC, AgaMiko requested changes

2022-01-03 14:26 UTC, AgaMiko commented on models/feature_extractors/resnet50_extractor.py
> +        self.model = timm.create_model(model_path, pretrained=True, num_classes=representation_size)
Try using torchvision models instead of timm library to avoid duplicating the same model as `cnn_extractor`

2022-01-04 17:48 UTC, mariaogryczak commented on models/feature_extractors/resnet50_extractor.py
> +        self.model = timm.create_model(model_path, pretrained=True, num_classes=representation_size)
corrected

2022-01-04 18:00 UTC, AgaMiko approved these changes

2022-01-05 17:37 UTC, aga0 approved these changes
LGTM

2022-01-06 18:21 UTC, MilenaOlech approved these changes

2022-01-07 09:10 UTC, merged