Added PretrainedTransformer.
hearai/hearai pull request #26
Opened 2022-01-15 14:49 UTC by wiktorfilipiuk

2022-01-15 15:34 UTC, majsylw requested changes
Please incorporate your pretraind tranfsormer into whole pipeline:
- add pretraind_transformer: https://github.com/hearai/hearai/blob/pretrained/models/model_loader.py#L16
- adjust parameters: https://github.com/hearai/hearai/blob/pretrained/models/model.py#L45
- put here `transformer_name="pretrained_transformer"` to test your implementation in pipeline: https://github.com/hearai/hearai/blob/pretrained/train.py#L123
- run `make format-check` to check if you formatted code well and if needed apply ` make format-apply`

2022-01-15 15:34 UTC, majsylw commented on models/transformers/pretrained_transformer.py
> +from transformers import HubertModel
I haven't seen updated requirements, did you used a transformers from huggingface?

2022-01-15 15:34 UTC, majsylw commented on models/transformers/pretrained_transformer.py
> +                 checkpoint='',
I think that you should provide here some example checkpint, maybe the same as in example file?

2022-01-15 15:34 UTC, majsylw commented on models/transformers/pretrained_transformer.py
> +                 add_softmax: bool = False):
This arguments are very problematic, becouse at the moement in whole pipeline we are using different one, please first modify also a line: https://github.com/hearai/hearai/blob/pretrained/models/model.py#L45

2022-01-15 15:47 UTC, majsylw commented on examples/mockup_transformer.py
> +    if (epoch % 1) == 0:
this condition is not necessary because you want to print results every time

2022-01-15 19:15 UTC, wiktorfilipiuk commented on examples/mockup_transformer.py
> +    if (epoch % 1) == 0:
Yeah, it's more like placeholder for further use if you want to start printing every n-th time. In this particular case, because there is very few epochs n=1 :)

2022-01-16 09:20 UTC, AgaMiko commented on models/transformers/pretrained_transformer.py
> +class PretrainedTransformer(nn.Module):
może "HubertTransformer" zamiast PretrainedTransformer bo wczytujemy tutaj tylko Huberta (z różnych checkpointów), a mogą pojawić się jeszcze w przyszłości inne pretrenowane transformery

2022-01-16 09:25 UTC, AgaMiko commented
> Please incorporate your pretraind tranfsormer into whole pipeline:
>     * put here `transformer_name="pretrained_transformer"` to test your implementation in pipeline: https://github.com/hearai/hearai/blob/pretrained/train.py#L123

@wiktorfilipiuk this one left

2022-01-16 09:29 UTC, AgaMiko reviewed
I feel like mockups functions are not necessary for the `pipeline/pipeline`. The transformer should work fine with the pipeline now, without mockup functions. If we will need this function we can just use your branch. You can rename this branch to mockups for future use

2022-01-21 12:03 UTC, closed without merging