Yaml
hearai/hearai pull request #67
Opened 2022-03-11 19:30 UTC by wiktorfilipiuk

2022-03-11 21:42 UTC, wiktorfilipiuk commented
Large chunks of commented arguments are still there in order to know how to write docstring later on. Please don't comment these parts for now :)

2022-03-12 14:25 UTC, AgaMiko commented on assets/sanity_check_data/train_config_sanity_gloss.yml
> +        transformer": [False, True]
`"` accidentally returned :)

2022-03-12 14:26 UTC, AgaMiko commented on assets/sanity_check_data/train_config_sanity_hamnosys.yml
> +        transformer": [False, True]
here `"` also -- to be removed

2022-03-12 14:29 UTC, AgaMiko requested changes
Looks good to me! Great job! 
Please remember to remove `"` from the freeze scheduler config.

2022-03-13 16:55 UTC, alicjak1519 reviewed
Your docstrings look great, they explain each parameter 😍

In the model classes implementations, there is a Dict typehint, but there is no "from typing import Dict"

2022-03-13 16:55 UTC, alicjak1519 commented on models/model.py
> +            freeze_scheduler (Dict): Dict containing information describing feature_extractor & transformer freezingz/unfreezing process.
typos:
- `containt` in 54, 62
-  `containg` in 66
- `freezingz` in 67

The same are in the model_for_pretraining.py ;)

2022-03-13 16:55 UTC, alicjak1519 commented on train.py
>          help="path to .yaml config file specyfing hyperparameters of different model sections."
`specyfing` --> `specifying`

2022-03-13 18:17 UTC, mariaogryczak approved these changes

2022-03-13 18:18 UTC, mariaogryczak commented
with changes proposed by @AgaMiko and @alicjak1519 I think it's ok :)

2022-03-13 18:35 UTC, AgaMiko approved these changes

2022-03-14 21:49 UTC, closed without merging