WIP: Update scheduler and optimizer
hearai/hearai pull request #70
Opened 2022-03-13 14:34 UTC by alicjak1519

According to the suggestion from the meeting, there are a couple of changes in the optimizers configuration.

2022-03-15 09:26 UTC, alicjak1519 commented
<img width="1364" alt="Screenshot 2022-03-15 at 10 23 20" src="https://user-images.githubusercontent.com/48221385/158346679-8c0eac35-9506-4441-a870-7d1dc48b821e.png">
According to Karol's suggestion, the scheduler and optimizer were updated. The green configuration, which seems to be the best, is optimizer: Adam, scheduler: OneCycleLR.

2022-03-15 09:30 UTC, alicjak1519 commented on models/model.py
> +        steps_per_epoch = self.steps_per_epoch // self.trainer.accumulate_grad_batches
According to the [comment](https://github.com/PyTorchLightning/pytorch-lightning/issues/1120#issuecomment-633641024)

2022-03-15 10:22 UTC, mariaogryczak approved these changes

2022-03-15 15:23 UTC, natcz approved these changes
Works for me (with reading the OneCycleLR docs knowledge).

2022-03-16 09:58 UTC, AgaMiko requested changes
I think that @karolmajek mentioned that onecyclelr has to be updated every step. Hence it should be moved from validation_epoch_end to validation_step. Can you check it?

2022-03-18 18:30 UTC, AgaMiko commented
Oh sorry, it should be in the training step of course! My fault!

2022-03-18 21:49 UTC, AgaMiko approved these changes

2022-03-22 07:22 UTC, alicjak1519 commented
After doing some improvements suggested by @AgaMiko and after merging main into this branch, I conducted three experimental pieces of training to compare scheduler/optimizer options again. Due to the time limit, my plots represent only 1 epoch (so the advantages of the new scheduler and optimizer can not be very reliable). However, taking into account @karolmajek intuition, I would like to merge this PR. :)

![Screenshot 2022-03-22 at 08 16 53](https://user-images.githubusercontent.com/48221385/159428463-52fa3429-e5e1-4b47-9ea4-c2c872238f0d.png)
![Screenshot 2022-03-22 at 08 16 58](https://user-images.githubusercontent.com/48221385/159428498-d7136bac-73eb-4a9f-998d-9e6eac8ead20.png)

2022-03-22 07:23 UTC, merged