Yaml rebased
hearai/hearai pull request #73
Opened 2022-03-14 21:34 UTC by wiktorfilipiuk

2022-03-14 21:37 UTC, majsylw commented on train_config.yml
> +    seed: 1234
previous experiments were with seed=2021
it ist important becouse the data split depends on that

2022-03-14 21:37 UTC, majsylw commented on datasets/dataset_creator.py
> +                 data_paths: Union[list, str],
I think it is List[str], in case of one dataset it is just a list with one string

2022-03-14 22:13 UTC, alicjak1519 approved these changes

2022-03-14 22:13 UTC, alicjak1519 commented on datasets/dataset_creator.py
> +                 data_paths: Union[list, str],
It was added just in case of putting a single string as a data_path in the config file. 
`data_path: "assets/sanity_check_data"` looks more intuitively than `data_path: ["assets/sanity_check_data"]`  :) That is why the method "_get_videos_root" was created. But it can be changed if you think that it is not a good practice. ;)

2022-03-15 08:10 UTC, AgaMiko commented on train.py
> +#         [
what about this? why is this commented instead removed?

2022-03-15 08:10 UTC, AgaMiko commented on train.py
> +#                            feature_extractor_model_path=model_config["feature_extractor"]["model_path"],
and here

2022-03-16 08:39 UTC, AgaMiko approved these changes
Great job!

2022-03-16 13:33 UTC, majsylw commented on datasets/dataset_creator.py
> +                 data_paths: Union[list, str],
is not just usuall list simpler to handle? then we will ahve only one data type

2022-03-16 13:35 UTC, majsylw commented
@wiktorfilipiuk before merging please look into readme and change it if it is needed.
I think that way of runing stuff changed, so the run examples must be corrected!

2022-03-16 13:37 UTC, majsylw requested changes
@wiktorfilipiuk before merging please look into readme and change it if it is needed.
I think that way of runing stuff changed, so the run examples must be corrected!

2022-03-17 19:55 UTC, MilenaOlech approved these changes

2022-03-18 10:30 UTC, majsylw commented on README.md
>  Run with a single dataset:
we need to add some description of yaml files here, where to find these parameter, how we can change them

2022-03-18 19:29 UTC, alicjak1519 commented on datasets/dataset_creator.py
> +                 data_paths: Union[list, str],
I think that both approaches have pros and cons but if you consider only `list` more convenient, I can change it of course. ;)

2022-03-18 21:58 UTC, wiktorfilipiuk commented on README.md
>  Run with a single dataset:
@majsylw please verify README  modifications.

2022-03-19 11:42 UTC, majsylw approved these changes

2022-03-19 11:42 UTC, majsylw commented on README.md
> +- `data_path` - (str) dir where input data is stored.
list of dirs ;-)

2022-03-19 11:42 UTC, majsylw commented on README.md
> +- `data_path` - (str) dir where input data is stored.
and like small think maybe it is worth to gather all dataset parameters together, like:
- num_segments
- landmarks
- time
- ect.

2022-03-19 19:17 UTC, AgaMiko commented
@wiktorfilipiuk? we are waiting for your awesome merge :dancers: please use the squash and merge option!

2022-03-20 20:35 UTC, merged